apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: offer-be
  namespace: argocd
spec:
  destination:
    namespace: offer-be
    server: https://kubernetes.default.svc
  project: default
  source:
    path: offer-be
    repoURL: git@github.com:price-offer/application-manifests/services.git
    targetRevision: test
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
