apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: offer-be
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 33
      - pause: {duration: 10}
      - setWeight: 66
      - pause: {duration: 10}
      - setWeight: 100
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: offer-be
  template:
    metadata:
      labels:
        app: offer-be
    spec:
      containers:
      - name: offer-be
        image: goharrm/offer-dev:953967c
        ports:
        - name: http
          containerPort: 7070
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
